module.exports = {
    'In what version (Java) was the elytra added to Minecraft?': '1.9',
    'In which version of Minecraft was the combat system revamped?': '1.9',
    'Which of these weapons is the best for breaking cobwebs?': 'Sword',
    'How much bone meal do you get from 1 bone?': '3',
    'There is an achievement related to pigs falling off cliffs.': 'True',
    'How big is the crafting table grid?': '3x3',
    'What happens to a villager when struck by lightning?': 'It turns into a zombie villager',
    'What happens to a pig when it is struck by lightning?': 'It turns into a Zombie Pigman',
    'Which beacon power is shown in the picture?': 'Regeneration',
    'A fire arrow can be shot without a Flame enchanted bow.': 'True',
    'Which of these ingredients is not needed to bake a cake?': 'Cocoa Beans',
    'Not all mobs receive fall damage.': 'True',
    'Who owns this skin?': 'Notch',
    'Which of these mobs drops gunpowder when killed?': 'Ghast',
    'Which of these mobs drops food when killed?': 'Pig',
    'Which Minecraft version (Java) added Bees?': '1.15',
    'Spiders drop cobwebs and spider eyes when killed.': 'False',
    'A Blaze can be killed with snowballs.': 'True',
    'In which version of Minecraft was the world border added?' : '1.8',
    'Which of these items might drop when killing an Enderman?': 'Ender Pearl',
    'Which of the following armor tiers provides the best defense?': 'Diamond',
    'How much obsidian is needed to craft an enchanting table?' : '4',
    'Which item is needed to increase the strength of a potion?': 'Glowstone Dust',
    'As of version 1.6, which name would turn a mob upside down?': 'Dinnerbone',
    'What happens if you name a sheep "jeb_"?': 'It alternates colors',
    'Which of these mobs can\'t swim?': 'Enderman',
    'How much wool is needed to craft a bed?': '3',
    'When was the Nether added to Minecraft?': '1.4.2',
    'How many different dimensions does Minecraft have?': '3',
    'In which version of Minecraft were End Cities added?': '1.9',
    'How can you control a pig while riding it?': 'Use a carrot on a stick',
    'How many obsidian pillars does the End dimension have?': '10',
    'What happens to a player\'s movement speed on Soul Sand, when it is placed on ice?': 'Slows down',
    'How many layers of blocks are generated on default superflat worlds?': '4',
    'Which of these mobs doesn\'t exist in Minecraft?': 'Shark',
    'What\'s the least amount of obsidian needed to craft a Nether portal?': '10',
    'Which action produces the Nausea effect?': 'Entering a Nether portal',
    'What aquatic hostile mob was added to Minecraft in the year 2014?': 'Guardians',
    'Which of these food items restores the most food points?': 'Mushroom Stew',
    'The Ender Dragon\'s fireballs can be deflected.': 'False',
    'Which of these mobs is not a type of Illager? (yes it\'s spelled right..)': 'Shulker',
    'What happens to an ender chest when broken with a regular diamond pickaxe?': 'Breaks permanently',
    'Which mob was the developer trying to make but accidentally created the Creeper?': 'Pig',
    'Which of the following provides the most amount of light?': 'Lantern',
    'What was Minecraft almost called?': 'Cave Game',
    'If you put an iron ingot into a crafting table, you can craft iron nuggets.' : 'True',
    'Which item is needed to brew a Splash Potion?': 'Gunpowder',
    'Which item is needed to brew a Lingering Potion?': 'Dragon’s Breath',
    'You can tell a wolf\'s health by their what?': 'Tail',
    'How many Eyes of Ender are needed to activate the End portal?': '12',
    'How many books are needed to craft an enchanting table?': '1',
    'Which mob is shown in the picture?': 'Blaze',
    'What happens to an ender chest when broken with a regular diamond pickaxe?': 'Ender chest drops',
    'What is the maximum building height (in blocks) in Minecraft?': '256',
    'What happens to a villager when struck by lightning?': 'It turns into a witch',
    'When does a Redstone torch turn off?': 'When the block it is attached to receives another power signal',
    'Herobrine was added to Minecraft in version 1.4 but got removed in 1.7.10.': 'False',
    'Which item is shown in the picture?': 'Nether Wart',
    'What\'s the highest level of Efficiency you can add to a diamond pickaxe using an enchantment table? ': '4',
    'How much damage (in hearts) does a Potion of Harming do?': '6',
    'Which mob is able to teleport?': 'Enderman',
    'Which item is needed to increase the duration of a potion?': 'Redstone Dust'
};
